# Generated by Django 5.0.3 on 2024-03-25 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_module', '0002_alter_maincategory_image_alter_subcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/jobs_images')),
                ('SubCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category_module.subcategory')),
            ],
        ),
    ]
