# Generated by Django 5.0.3 on 2024-03-31 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_module', '0002_remove_job_image_job_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_pictures',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='job_module.job'),
        ),
    ]
