# Generated by Django 5.0.3 on 2024-04-01 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_module', '0004_alter_job_pictures_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_pictures',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='job_module.job'),
        ),
    ]
