# Generated by Django 5.0.3 on 2024-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_module', '0005_alter_job_pictures_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_pictures',
            name='image',
            field=models.ImageField(upload_to='images/job_images'),
        ),
    ]
