# Generated by Django 5.0.3 on 2024-04-01 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_module', '0006_alter_job_pictures_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='main_picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_pictures_of', to='job_module.job_pictures'),
        ),
    ]
