# Generated by Django 5.0.3 on 2024-04-01 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_module', '0007_job_main_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='main_picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_picture_of', to='job_module.job_pictures'),
        ),
    ]
