# Generated by Django 5.0.3 on 2024-04-01 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_module', '0012_alter_job_comments_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_comments',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='job_module.job'),
        ),
    ]
