# Generated by Django 5.0.4 on 2024-04-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_module', '0014_skill_job_approximation_cph_job_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experience',
            new_name='experiences',
        ),
    ]
