# Generated by Django 5.0.3 on 2024-04-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_module', '0002_alter_maincategory_image_alter_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
